# Generated by Django 2.1.5 on 2019-02-04 10:58

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actuaciones', '0002_auto_20171003_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relaciones',
            name='instrumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='actuaciones.instrumentos'),
        ),
        migrations.AlterField(
            model_name='samberos',
            name='backstage',
            field=models.BooleanField(default=False, help_text='Si el sambero esta activo, pero no tocando instrumentos ... '),
        ),
        migrations.AlterField(
            model_name='samberos',
            name='instrumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='actuaciones.instrumentos'),
        ),
        migrations.AlterField(
            model_name='samberos',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='samberos',
            name='movil',
            field=models.CharField(blank=True, help_text='Este es el numero para los SMS', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='samberos',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
