# Generated by Django 2.1.7 on 2019-10-04 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actuaciones', '0005_auto_20191004_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuaciones',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actuaciones',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
