# Generated by Django 3.2.4 on 2021-06-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuaciones', '0006_auto_20191004_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samberos',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
